name:                CourseraMachineLearning
version:             0.1.0.0
github:              "mchav/CourseraMachineLearning"
license:             BSD3
author:              "Michael Chavinda"
maintainer:          "mschavinda@gmail.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mchav/CourseraMachineLearning#readme>

dependencies:
- base >= 4.7 && < 5
- hmatrix
- gnuplot
- directory
- statistics
- vector
- ihaskell
- ihaskell-gnuplot
- hmatrix-csv
- bytestring
- cassava
- QuickCheck
- deepseq

library:
  source-dirs: src

executables:
  CourseraMachineLearning-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CourseraMachineLearning

tests:
  CourseraMachineLearning-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CourseraMachineLearning

